Repository Alfresco/alfresco-docker-base-tomcat, pull requests merged in 2022-03, with the labels that each got.

#69 OPSEXP-1295: removes python-lxml for security reasons
  .github/workflows/main.yml
Labels: PR: unreviewed

#72 OPSEXP-1317 Remove tomcat 10 base image
  Dockerfile
  README.md
Labels: PR: reviewed-approved

#71 OPSEXP-1315 fix for CVE-2022-23181
  .github/workflows/main.yml
  Dockerfile
  README.md
Labels: PR: reviewed-approved

#70 OPSEXP-1294 Update README for new tag naming convention
  README.md
Labels: PR: partially-approved
